---
# TODO: Travis has Nix-specific infrastructure; but Sirio is not advanced
#+  enough to properly Derive this codebase ... so let there be hacks ;)

language: c
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty

    - os: osx

script:
  - ./nix-toolchain.sh
...
